# Generated by Django 4.0 on 2022-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=255, verbose_name='Данные')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('request_date', models.DateTimeField(auto_now=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
