# Generated by Django 4.0 on 2022-12-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmodel',
            old_name='code',
            new_name='exit_code',
        ),
    ]
